import 'package:get/get.dart';

class Translate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'home': 'Home',
          'login': 'Sign In',
          'register': 'Register',
          'remeber': 'Remeber',
          'logout': 'Logout',
          'logout_success': 'ອອກຈາກລະບົບສໍາເລັດ',
          'not_logged_in_yet': 'Not logged in yet',
          'name': 'Name',
          'lastname': 'Lastname',
          'fullname': 'Fullname',
          'phone': 'Phone',
          'password': 'Password',
          'confirm_password': 'Confirm password',
          'forget_password': 'Forget password?',
          'service_shipping': 'Service Shipping',
          'profile': 'Profile',
          'order': 'Order',
          'ok': 'OK',
          'cancel': 'Cancel',
          'do_you_want_to_logout?': 'Do you want to logout ?',
          'village': 'Village',
          'district': 'District',
          'province': 'Province',
          'select_province': 'Select Province',
          'select_district': 'Select District',
          'select_village': 'Select Village',
          'setting': 'Setting',
          'setting_lan': 'Setting language',
          'service': 'Service',
          'welcome': 'Welcome',
          'please_enter_login': 'Please enter login!',
          'about': 'About',
          'my_order': 'My Order',
          'privacy_policy': 'Privacy policy',
          'login_success': 'Login success',
          'conf_password': 'Confirm Password',
          'list': 'List',
          'forgot_pass': 'Forgot password?',
          'details': 'Details',
          'address': 'Address',
          'edit': 'Edit',
          'cart': 'Cart',
          'not_found_product_in_cart': 'Not found product in Cart',
          'none': 'None',
          'please_enter_all_filed': 'Please enter all field',
          'please_enter_the_complete_information':
              'Please enter the complete information',
          'address_detail': 'Address detail',
          'your_location': 'Your Location',
          'total_price': 'Total Price',
          'price': 'Price',
          'add_to_cart': 'Add To Cart',
          'added': 'Added',
          'payment': 'Payment',
          'delivery_address': 'Delivery Address',
          'language': 'Language',
          'choose_language': 'Choose Language',
          'search': 'Search',
          'suggestion': 'Suggestions',
          'view_all': 'View all',
          'product_all': 'All product',
          'something_wrong': 'Something wrong',
          'i_accept_privacy_policy': 'I accept privacy policies from CIT GROUP',
          'loading': 'Loading...',
          'product_list': 'Product List',
          'review': 'Review',
          'edit_comment': 'Edit Comment',
          'comment': 'Comment',
          'skip': 'Skip',
          'bill_no': 'Bill no',
          'date': 'Date',
          'time': 'Time',
          'confirm_receive': 'Confirm Receive',
          'do_you_received_product': 'Are you received products?',
          'order_detail': 'Order Detail',
          'sub_total': 'Sub total',
          'total': 'Total',
          'no_history': 'No history',
          'canceled': 'Canceled',
          'checking': 'Checking',
          'paid': 'Paid',
          'delivered': 'Delivered',
          'in_process': 'In process',
          'delivery': 'Delivery',
          'confirm': 'Confirm',
          'edit_profile': 'Edit Profile',
          'success': 'Success',
          'retry': 'Retry',
          'transfer': 'Transfer',
          'notice': 'Notice',
          'after_payment_msg':
              'Please press button check payment for checking your paid after transfer BCEL.',
          'order_success': 'Order Success',
          'check_payment': 'Check Payment',
          'go_to_payment': 'Go to Payment',
          'confirm_address': 'Confirm Address',
          'save_success': 'Save success',
          'do_you_want_to_cancel_this_order':
              'Do you want to cancel this order?',
          'register_success': 'Register success',
          'call': 'Call to inquire',
          'sold_out': 'Sold Out',
          'add_location': 'Add Location',
          'edit_location': 'Edit Location',
          'save': 'Save',
          'do_you_want_to_delete': 'Do you want to delete',
          'no_data': 'No data',
          'select_address': 'Select Address',
          'please_select_address': 'Please select address!',
          'my_location': 'My Location',
          'do_you_want_to_logout': 'Do you want to logout?',
          'overview': 'Overview',
          'review': 'Reviews',
          'me': 'Me',
          'report': 'Report',
          'forgot_password': 'Forgot Password',
          'reset_pass': 'Reset Password',
          'enter_you_phone_to_reset': 'Enter your phone to reset your password',
          'please_enter_phone': 'Please enter phone!',
          'phone_is_not_regiseted': 'Phone is not registered',
          'password_not_match': 'Passwort not match!',
          'code_otp_is_incorrect': 'code OTP is incorrect',
          'please_enter_otp_code': 'Please enter otp code!',
          'send_otp': 'Send OTP',
          'do_not_send_otp': 'Do not send OTP ?',
          'we_have_sent_an_otp_to': 'We have sent an OTP to',
          'please_enter_it_below': 'Please enter it below.',
          'new_password': 'New password',
          'phone_is_regiseted': 'Phone is registered!',
          'not_found_payment': 'Payment Not Found!',
          'added_to_cart': 'Add To Cart',
          'you_need_accept_privacy_policy': 'You need accept privacy policy',
          'your_pass_is_incorrect': 'Your password is incorrect!',
          'not_found_interesting_on_this_app':
              'Not found interesting on this app',
          'i_receive_too_many_notification': 'I receive too many notification',
          'i_found_many_bug': 'I found many bug',
          'difficult_to_use.': 'Difficult to use',
          'other': 'Other',
          'submit': 'Submit',
          'write_more': 'Write more....',
          'please_make_sure_to_delete_this_account':
              'Please make sure to delete this account',
          'your_account_has_been_deleted': 'Your account has been deleted',
          'delete_account': 'Delete Account',
          'change_password': 'Change password',
          'please_enter_all_field': 'Please enter all field',
          'pass_does_math': 'Password does match',
          'lao': 'Lao',
          'english': 'English',
          'chinese': 'Chinese',
          'transaction_history': 'Transaction history',
          'personal_information': 'Personal information',
          'shop': 'Shop',
          'amount': 'Amount',
          'new': 'New',
          'completed': 'Completed',
          'product': 'Product',
          'qty': 'Qty',
          'discount': 'Discount',
          'search_for_restaurants': 'Search for restaurants..',
          'recommended_restaurants': 'Recommended restaurants',
          'close': 'Close',
          'food_list': 'Food list',
          'map': 'Map',
          'there_is_no_food_menu_yet.': 'There is no food menu yet.',
          'there_are_no_reviews_yet': 'There are no reviews yet.',
          'scan_qrcode': 'Scan Qrcode',
          'rescan': 'Rescan',
          'this_table_has_already_been_reserved':
              'This table has already been reserved.',
          'the_QR_code_is_invalid': 'The QR code is invalid. Please try again.',
          'welcome_to': 'Welcome to',
          'table': 'Table',
          'do_you_want_to_order_food': 'Do you want to order food?',
          'choose_food': 'Choose food',
          'food': 'food',
          'drink': 'Drink',
          'ordered_items': 'Ordered items',
          'food_order_completed.': 'Food order completed.',
          'please_login_first': 'Please Login first.',
          'please_choose_a_meal_first': 'Please choose a meal first.',
          'already_have_an_account': 'Already have an account?',
          'no_account_yet':'No account yet?',

        },
        'la_LA': {
          'home': 'ໜ້າຫຼັກ',
          'login': 'ເຂົ້າໃຊ້ງານ',
          'remeber': 'ຈື່ຂ້ອຍໄວ້',
          'register': 'ລົງທະບຽນ',
          'logout': 'ອອກຈາກລະບົບ',
          'logout_success': 'ອອກຈາກລະບົບສໍາເລັດ',
          'not_logged_in_yet': 'ຍັງບໍໄດ້ເຂົ້າສູ່ລະບົບ',
          'name': 'ຊື່',
          'fullname': 'ຊື່ ແລະ ນາມສະກຸນ',
          'phone': 'ເບີໂທ',
          'password': 'ລະຫັດຜ່ານ',
          'confirm_password': 'ຢືນຢັນລະຫັດຜ່ານ',
          'forget_password': 'ລືມລະຫັດຜ່ານ?',
          'service_shipping': 'ບໍລິການຂົນສົ່ງສິນຄ້າ',
          'service_transport': 'ບໍລິການຂົນສົ່ງໂດຍສານ',
          'service_fresh': 'ບໍລິການຕະຫຼາດສົດ',
          'service_fresh_delivery': 'ບໍລິການຈ່າຍຕະຫຼາດ',
          'profile': 'ໂປລໄຟລ',
          'order': 'ອໍເດີ້',
          'ok': 'ຕົກລົງ',
          'report': 'ລາຍງານ',
          'cancel': 'ຍົກເລີກ',
          'do_you_want_to_logout?': 'ທ່ານຕ້ອງການອອກຈາກລະບົບຫຼືບໍ່?',
          'lastname': 'ນາມສະກຸນ',
          'village': 'ບ້ານ',
          'district': 'ເມືອງ',
          'province': 'ແຂວງ',
          'select_province': 'ເລືອກແຂວງ',
          'select_district': 'ເລືອກເມືອງ',
          'select_village': 'ເລືອກບ້ານ',
          'setting': 'ຕັ້ງຄ່າ',
          'setting_lan': 'ຕັ້ງຄ່າພາສາ',
          'service': 'ການບໍລິການ',
          'shop': 'ຮ້ານ',
          'welcome': 'ຍີນດີຕ້ອນຮັບ',
          'please_enter_login': 'ກະລຸນາເຂົ້າສູ່ລະບົບກ່ອນ',
          'about': 'ກ່ຽວກັບ',
          'my_order': 'ອໍເດີຂອງຂ້ອຍ',
          'me': 'ຂ້ອຍ',
          'privacy_policy': 'ນະໂຍບາຍ',
          'login_success': 'ເຂົ້າສູ່ລະບົບສຳເລັດ',
          'conf_password': 'ຢືນຢັນລະຫັດຜ່ານ',
          'list': 'ລາຍການ',
          'forgot_pass': 'ລືມລະຫັດຜ່ານ?',
          'details': 'ລາຍລະອຽດ',
          'address': 'ທີ່ຢູ່',
          'edit': 'ແກ້ໄຂ',
          'cart': 'ກະຕ່າ',
          'not_found_product_in_cart': 'ບໍ່ມີສີນຄ້າໃນກະຕ່າ',
          'none': 'ບໍ່ມີ',
          'please_enter_all_filed': 'ກະລຸນາຕື່ມຂໍ້ມູນໃຫ້ຄົບ!',
          'address_detail': 'ລາຍລະອຽດທີ່ຢູ່',
          'your_location': 'ທີ່ຢູ່ຂອງທ່ານ',
          'total_price': 'ລາຄາລວມ',
          'price': 'ລາຄາ',
          'add_to_cart': 'ເພີ່ມໃສ່ກະຕ່າ',
          'added': 'ເພີ່ມແລ້ວ',
          'payment': 'ການຊຳລະ',
          'delivery_address': 'ທີ່ຢູ່ຈັດສົ່ງ',
          'language': 'ພາສາ',
          'choose_language': 'ເລືອກພາສາ',
          'search': 'ຄົ້ນຫາ',
          'suggestion': 'ສີນຄ້າແນະນຳ',
          'view_all': 'ເບີ່ງທັງໝົດ',
          'product_all': 'ສີນຄ້າທັງໝົດ',
          'something_wrong': 'ມີບາງຢ່າງຜີດພາດ',
          'i_accept_privacy_policy': 'ຍອມຮັບນະໂຍບາຍຈາກ CIT GROUP',
          'loading': 'ກຳລັງໂຫຼດ',
          'review_product': 'ລີວີວສີນຄ້າ',
          'review': 'ລີວີວ',
          'product_list': 'ລາຍການສີນຄ້າ',
          'edit_comment': 'ແກ້ໄຂຄຳຄິດເຫັນ',
          'comment': 'ສະແດງຄຳຄິດເຫັນ',
          'skip': 'ຂ້າມ',
          'bill_no': 'ລະຫັດໃບບີນ',
          'date': 'ວັນທີ',
          'time': 'ເວລາ',
          'confirm_receive': 'ຢືນຢັນໄດ້ຮັບເຄື່ອງ',
          'do_you_received_product': 'ທ່ານໄດ້ຮັບສິນຄ້າແລ້ວ ຫຼື ບໍ່?',
          'order_detail': 'ລາຍລະອຽດອໍເດີ້',
          'sub_total': 'ລວມ',
          'total': 'ລວມທັງໝົດ',
          'no_history': 'ຍັງບໍ່ມີປະຫວັດ',
          'canceled': 'ຍົກເລີກ',
          'checking': 'ກຳລັງກວດສອບ',
          'paid': 'ຊຳລະເງີນແລ້ວ',
          'delivered': 'ຈັດສົ່ງສຳເລັດ',
          'in_process': 'ກຳລັງດຳເນີນການ',
          'delivery': 'ກຳລັງຈັດສົ່ງ',
          'confirm': 'ຢືນຢັນ',
          'edit_profile': 'ແກ້ໄຂໂປລໄຟລ',
          'success': 'ສຳເລັດ',
          'retry': 'ລອງໃຫມ່',
          'transfer': 'ໂອນຜ່ານ',
          'notice': 'ໝາຍເຫດ',
          'after_payment_msg':
              'ຫຼັງຈາກຊຳລະຜ່ານ BCEL ແລ້ວກະລຸນາກົດປຸ່ມກວດສອບການຊຳລະເພື່ອຢືນຢັນການຊຳລະ.',
          'order_success': 'ການສັ່ງຊື້ສຳເລັດ',
          'check_payment': 'ກວດສອບການຊຳລະ',
          'go_to_payment': 'ໄປທີການຊຳລະ',
          'confirm_address': 'ຢືນຢັນທີ່ຢູ່',
          'save_success': 'ບັນທືກສຳເລັດ',
          'do_you_want_to_cancel_this_order':
              'ທ່ານຕ້ອງການຍົກເລີກທຸລະກຳນີ້ຫຼືບໍໍ?',
          'register_success': 'ລົງທະບຽນສຳເລັດ',
          'call': 'ໂທສອບຖາມ',
          'sold_out': 'ສິນຄ້າໝົດ',
          'add_location': 'ເພີ່ມທີ່ຢູ່ຈັດສົ່ງ',
          'edit_location': 'ແກ້ໄຂທີ່ຢູ່ຈັດສົ່ງ',
          'save': 'ບັນທືກ',
          'do_you_want_to_delete': 'ທ່ານຕ້ອງການລົບ ຫຼື ບໍ່?',
          'no_data': 'ຍັງບໍ່ຂໍ້ມູນ',
          'select_address': 'ເລືອກທີ່ຢູ່ຈັດສົ່ງ',
          'please_select_address': 'ກະລຸນາເລືອກທີ່ຢູ່ຈັດສົ່ງ!',
          'my_location': 'ທີ່ຢູ່ຂອງຂ້ອຍ',
          'do_you_want_to_logout': 'ຕ້ອງການອອກຈາກລະບົບ ຫຼື ບໍ່?',
          'overview': 'ພາບລວມ',
          'review': 'ລີວີວ',
          'forgot_password': 'ລືມລະຫັດຜ່ານ',
          'reset_pass': 'ກູ້ຄືນລະຫັດຜ່ານ',
          'enter_you_phone_to_reset': 'ປ້ອນເບີໂທຂອງທ່ານເພື່ອກູ້ຄືນລະຫັດຜ່ານ',
          'please_enter_phone': 'ກະລຸນາປ້ອນເບີໂທຂອງທ່ານ!',
          'please_enter_the_complete_information': 'ກະລຸນາປ້ອນຂໍມູນໃຫ້ຄົບ!',
          'phone_is_not_regiseted': 'ເບີໂທຍັງບໍ່ໄດ້ລົງທະບຽນ!',
          'password_not_match': 'ລະຫັດບໍ່ຕົງກັນ!',
          'code_otp_is_incorrect': 'ລະຫັດ OTP ບໍ່ຖືກຕ້ອງ!',
          'please_enter_otp_code': 'ກະລຸນາປ້ອນລະຫັດ OTP!',
          'send_otp': 'ສົ່ງລະຫັດ',
          'do_not_send_otp': 'ຍັງບໍ່ໄດ້ຮັບລະຫັດ?',
          'we_have_sent_an_otp_to': 'ພວກເຮົາສົ່ງລະຫັດ OTP ໄປຍັງ ',
          'please_enter_it_below': 'ກະລຸນາປ້ອນລະຫັດໃສ່ດ້ານລຸ່ມນີ້.',
          'new_password': 'ລະຫັດໃຫມ່',
          'phone_is_regiseted': 'ເບີໂທນີ້ໄດ້ລົງທະບຽນແລ້ວ!',
          'not_found_payment': 'ຍັງບໍ່ທັນມີການຊຳລະເງີນ',
          'added_to_cart': 'ເພີ່ມເຂົ້າກະຕ່າແລ້ວ',
          'you_need_accept_privacy_policy':
              'ທ່ານຕ້ອງຍອມຮັບນະໂຍບາຍຄວາມເປັນສ່ວນຕົວກ່ອນ',
          'your_pass_is_incorrect': 'ລະຫັດຜ່ານບໍ່ຖືກຕ້ອງ',
          'not_found_interesting_on_this_app': 'ບໍ່ພົບສີ່ງທີ່ນ່າສົນໃຈໃນແອັບ',
          'i_receive_too_many_notification': 'ໄດ້ຮັບແຈ້ງເຕືອນຫຼາຍໂພດ',
          'i_found_many_bug': 'ເຈີບັນຫາຫຼາຍ',
          'difficult_to_use.': 'ໃຊ້ງານຍາກ',
          'other': 'ອື່ນໆ',
          'submit': 'ຢືນຍັນ',
          'write_more': 'ຂຽນເພີ່ມເຕີມ....',
          'please_make_sure_to_delete_this_account':
              'ທ່ານຕ້ອງການລົບບັນຊີນີ້ ແທ້ ບໍ່​?',
          'your_account_has_been_deleted': 'ບັນຊີຂອງທ່ານຖືກລົບແລ້ວ',
          'delete_account': 'ລົບບັນຊີ',
          'change_password': 'ປ່ຽນລະຫັດຜ່ານ',
          'please_enter_all_field': 'ກະລຸນາປ້ອນຂໍ້ມູນກ່ອນ',
          'pass_does_math': 'ລະຫັດບໍ່ຕົງກັນ',
          'lao': 'ລາວ',
          'english': 'ອັງກິດ',
          'chinese': 'ຈີນ',
          'transaction_history': 'ປະຫວັດການເຮັດທຸລະການ',
          'personal_information': 'ຂໍ້ມູນສ່ວນຕົວ',
          'amount': 'ຈໍານວນ',
          'new': 'ໃໝ່',
          'completed': 'ສໍາເລັດແລ້ວ',
          'product': 'ສິນຄ້າ',
          'qty': 'ຈໍານວນ',
          'discount': 'ສ່ວນຫຼຸດ',
          'search_for_restaurants': 'ຄົ້ນຫາຮ້ານອາຫານ..',
          'recommended_restaurants': 'ຮ້ານອາຫານທີ່ເນະນໍາ',
          'close': 'ປິດ',
          'food_list': 'ລາຍການອາຫານ',
          'there_is_no_food_menu_yet.': 'ມີລາຍການອາຫານ.',
          'map': 'ແຜນທີ່',
          'there_are_no_reviews_yet': 'ຍັງບໍ່ມີລາຍການລີວິວ',
          'scan_qrcode': 'ສະແກນ Qrcode',
          'rescan': 'ສະແກນໃໝ່',
          'this_table_has_already_been_reserved': 'ໂຕະນີ້ມີຄົນສັ່ງກ່ອນແລ້ວ.',
          'the_QR_code_is_invalid': 'QR code ບໍຖືກຕ້ອງກະລຸນາລອງໃໝ່.',
          'welcome_to': 'ຍີນດີຕ້ອນຮັບສູ່',
          'table': 'ໂຕະ',
          'do_you_want_to_order_food': 'ທ່ານຕ້ອງການສັ່ງອາຫານເລີຍບໍ?',
          'choose_food': 'ເລືອກອາຫານ',
          'food': 'ອາຫານ',
          'drink': 'ເຄື່ອງດື່ມ',
          'ordered_items': 'ລາຍການທີ່ສັ່ງ',
          'food_order_completed.': 'ສັ່ງອາຫານສໍາເລັດແລ້ວ',
          'please_login_first': 'ກະລຸນາເຂົ້າສູ່ລະບົບກ່ອນ.',
          'please_choose_a_meal_first': 'ກະລຸນາເລືອກອາຫານກ່ອນ..',
          'already_have_an_account': 'ມີບັນຊີແລ້ວ',
          'no_account_yet':'ຍັງບໍທັນມີບັນຊີ?',
        },
      };
}
